################################### German language #####################################
[de]
languageName = "De"
languageCode = "de-de"
contentDir = "content/german"
weight = 1
[de.params]
footer_content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore dolore magna aliquyam eratnonumy onsetetur"
# copyright
copyright = "Copyright by DataFortress.cloud"

################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
[en.params]
footer_content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore dolore magna aliquyam eratnonumy onsetetur"
# copyright
copyright = "Copyright by DataFortress.cloud"



################################### French language #####################################
[fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 3
[fr.params]
footer_content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore dolore magna aliquyam eratnonumy onsetetur"
# copyright
copyright = "Copyright by DataFortress.cloud"