############# French navigation ##############
# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Wie es funktioniert"
url = "how-it-works/"
weight = 2

[[main]]
name = "Preise"
url = "pricing/"
weight = 3

[[main]]
name = "Kontakt"
url = "contact/"
weight = 4

[[main]]
name = "Über uns"
weight = 5
hasChildren = true

  [[main]]
  parent = "Über uns"
  name = "Tutorials"
  url = "/blog"

  [[main]]
  parent = "Über uns"
  name = "Mein Abonnement"
  url = "https://billing.stripe.com/p/login/test_bIY6pJesg2dC9iMdQQ"

  [[main]]
  parent = "Über uns"
  name = "AGB"
  url = "terms-conditions/"

  [[main]]
  parent = "Über uns"
  name = "Privatsphären-Information"
  url = "privacy-policy/"

  [[main]]
  parent = "Über uns"
  name = "Impressum"
  url = "impressum/"

# Footer menu
[[footer]]
name = "Kontakt"
url = "contact/"
weight = 1

[[footer]]
name = "AGB"
url = "terms-conditions/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3